import type { KaspaNetwork } from "../shared/protocol";

export interface EvmConfig { name:string;chainId:number;rpc:string;explorerApi:string;nativeSymbol:string;wrapped:string }
export function evmConfig(network:KaspaNetwork):EvmConfig {
  if(network==="kasplex")return{name:"Kasplex zkEVM",chainId:202555,rpc:"https://evmrpc.kasplex.org",explorerApi:"https://api-explorer2.kasplex.org/api/v2",nativeSymbol:"KAS",wrapped:"0x2c2Ae87Ba178F48637acAe54B87c3924F544a83e"};
  if(network==="igra")return{name:"Igra Network",chainId:38833,rpc:"https://rpc.igralabs.com:8545",explorerApi:"https://explorer.igralabs.com/api/v2",nativeSymbol:"iKAS",wrapped:"0x17Ec7E1768c813E2a3a9b0f94A35605CA520C242"};
  throw new Error("The selected network is not EVM compatible.");
}
let rpcId=0;
export async function evmRpc(network:KaspaNetwork,method:string,params:unknown[]=[]){
  const config=evmConfig(network),controller=new AbortController(),timer=setTimeout(()=>controller.abort(),12_000);
  try{const response=await fetch(config.rpc,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({jsonrpc:"2.0",id:++rpcId,method,params}),signal:controller.signal});
    if(!response.ok)throw new Error(`${config.name} RPC returned HTTP ${response.status}.`);const decoded=await response.json();if(decoded.error)throw new Error(String(decoded.error.message??"EVM RPC error"));return decoded.result;
  }finally{clearTimeout(timer)}
}
export function hexBig(value:unknown){const raw=String(value??"0x0").replace(/^0x/,"");return BigInt(`0x${raw||"0"}`)}
export function toHex(value:bigint){return`0x${value.toString(16)}`}
export function formatUnits(value:bigint,decimals:number,visible=8){const raw=value.toString().padStart(decimals+1,"0"),whole=raw.slice(0,-decimals)||"0",fraction=(decimals?raw.slice(-decimals).slice(0,visible):"").replace(/0+$/,"");return fraction?`${whole}.${fraction}`:whole}
export function parseUnits(value:string,decimals:number){if(!/^\d+(\.\d+)?$/.test(value))throw new Error("Enter a valid amount.");const[whole,fraction=""]=value.split(".");if(fraction.length>decimals)throw new Error(`Use no more than ${decimals} decimal places.`);return BigInt(whole!)*10n**BigInt(decimals)+BigInt(fraction.padEnd(decimals,"0")||"0")}
async function trustedContracts(network:KaspaNetwork){const config=evmConfig(network),trusted=new Set([config.wrapped.toLowerCase()]);try{const response=await fetch("https://api.katbridge.com/token-pair"),decoded=await response.json(),rows=Array.isArray(decoded)?decoded:decoded.result??decoded.data??[];for(const row of rows){const chain=Number(row.chainId??row.chain_id??row.l2_chain_id),address=String(row.l2Contract??row.l2_contract??row.contractAddress??row.l2_address??"");if(row.is_active!==false&&chain===config.chainId&&/^0x[0-9a-fA-F]{40}$/.test(address))trusted.add(address.toLowerCase())}}catch{}return trusted}
export async function evmSnapshot(network:KaspaNetwork,address:string){const config=evmConfig(network);const[balance,tokenResponse,trusted]=await Promise.all([evmRpc(network,"eth_getBalance",[address,"latest"]),fetch(`${config.explorerApi}/addresses/${address}/token-balances`),trustedContracts(network)]);if(!tokenResponse.ok)throw new Error(`L2 explorer returned HTTP ${tokenResponse.status}.`);const rows=await tokenResponse.json();const tokens=(Array.isArray(rows)?rows:[]).map((row:any)=>{const token=row.token??{},contract=String(token.address_hash??token.address??"");return{contract,symbol:String(token.symbol??"TOKEN").toUpperCase(),name:String(token.name??"Unknown token"),decimals:Number(token.decimals??18),rawBalance:String(row.value??0),balance:formatUnits(BigInt(row.value??0),Number(token.decimals??18)),trusted:trusted.has(contract.toLowerCase()),iconUrl:token.icon_url??null}}).filter((token:any)=>BigInt(token.rawBalance)>0n&&token.contract);
  return{evm:true,address,balanceRaw:hexBig(balance).toString(),balance:formatUnits(hexBig(balance),18),balanceKas:Number(formatUnits(hexBig(balance),18,12)),nativeSymbol:config.nativeSymbol,tokens};}
export async function evmHistory(network:KaspaNetwork,address:string){const config=evmConfig(network);const responses=await Promise.all([fetch(`${config.explorerApi}/addresses/${address}/transactions`),fetch(`${config.explorerApi}/addresses/${address}/token-transfers`)]);if(!responses[0].ok)throw new Error("L2 activity is unavailable.");const native=await responses[0].json(),items:any[]=[];for(const row of native.items??[]){const gas=BigInt(row.gas_used??0)*BigInt(row.gas_price??0);items.push({transactionId:row.hash,from:row.from?.hash??row.from??"",to:row.to?.hash??row.to??"",amount:formatUnits(BigInt(row.value??0),18),symbol:config.nativeSymbol,fee:formatUnits(gas,18,18),blockTime:Date.parse(row.timestamp??"")||0,status:String(row.result??row.status??"")})}if(responses[1].ok){const tokens=await responses[1].json();for(const row of tokens.items??[]){const token=row.token??{},total=row.total??{};items.push({transactionId:row.transaction_hash??row.tx_hash,from:row.from?.hash??row.from??"",to:row.to?.hash??row.to??"",amount:formatUnits(BigInt(total.value??row.value??0),Number(token.decimals??total.decimals??18)),symbol:String(token.symbol??"TOKEN").toUpperCase(),fee:null,blockTime:Date.parse(row.timestamp??"")||0,status:"success"})}}return items.sort((a,b)=>b.blockTime-a.blockTime).slice(0,50)}
export function erc20Data(recipient:string,amount:bigint){return`0xa9059cbb${recipient.slice(2).padStart(64,"0")}${amount.toString(16).padStart(64,"0")}`}
export async function evmTransactionFields(network:KaspaNetwork,from:string,to:string,value:bigint,data:string){const[nonce,gasPrice,gas]=await Promise.all([evmRpc(network,"eth_getTransactionCount",[from,"pending"]),evmRpc(network,"eth_gasPrice",[]),evmRpc(network,"eth_estimateGas",[{from,to,value:toHex(value),...(data?{data}:{})}])]);return{nonce:hexBig(nonce),gasPrice:hexBig(gasPrice),gas:hexBig(gas)}}
export async function waitReceipt(network:KaspaNetwork,hash:string){for(let i=0;i<30;i++){const receipt=await evmRpc(network,"eth_getTransactionReceipt",[hash]);if(receipt){if(hexBig(receipt.status)!==1n)throw new Error("The transaction failed on-chain.");return receipt}await new Promise(resolve=>setTimeout(resolve,2000))}throw new Error("Transaction broadcast, but confirmation is pending.")}
