import{PROVIDER_CHANNEL,type ProviderEvent,type ProviderMethod,type ProviderResponse,type KaspaNetwork}from"../shared/protocol";
type Listener=(...args:unknown[])=>void;
class KaspireProvider{readonly isKaspire=true;readonly version="1.0.0";private listeners=new Map<string,Set<Listener>>();constructor(){addEventListener("message",event=>{const message=event.data as ProviderEvent;if(event.source!==window||message?.channel!==PROVIDER_CHANNEL||message.direction!=="event")return;this.emit(message.event,message.data)})}private emit(event:string,data:unknown){for(const listener of this.listeners.get(event)??[])try{listener(data)}catch{}}request<T=unknown>({method,params}:{method:ProviderMethod;params?:unknown}):Promise<T>{const id=crypto.randomUUID();return new Promise((resolve,reject)=>{const timeout=setTimeout(()=>{removeEventListener("message",receive);reject(new Error("Kaspire request timed out."))},360000);const receive=(event:MessageEvent<ProviderResponse>)=>{const r=event.data;if(event.source!==window||r?.channel!==PROVIDER_CHANNEL||r.direction!=="response"||r.id!==id)return;clearTimeout(timeout);removeEventListener("message",receive);r.error?reject(Object.assign(new Error(r.error.message),r.error)):resolve(r.result as T)};addEventListener("message",receive);postMessage({channel:PROVIDER_CHANNEL,direction:"request",id,method,params},location.origin)})}on(event:string,listener:Listener){const set=this.listeners.get(event)??new Set<Listener>();set.add(listener);this.listeners.set(event,set);return this}removeListener(event:string,listener:Listener){this.listeners.get(event)?.delete(listener);return this}async requestAccounts(){const accounts=await this.request<string[]>({method:"requestAccounts"});this.emit("accountsChanged",accounts);return accounts}getAccounts(){return this.request<string[]>({method:"getAccounts"})}getNetwork(){return this.request<KaspaNetwork>({method:"getNetwork"})}async switchNetwork(network:KaspaNetwork){const selected=await this.request<KaspaNetwork>({method:"switchNetwork",params:{network}});this.emit("networkChanged",selected);return selected}getPublicKey(){return this.request<string>({method:"getPublicKey"})}getBalance(){return this.request({method:"getBalance"})}getUtxoEntries(){return this.request({method:"getUtxoEntries"})}async disconnect(){const result=await this.request({method:"disconnect"});this.emit("accountsChanged",[]);this.emit("disconnect",{code:4900,message:"Kaspire disconnected this site."});return result}signMessage(message:string,address?:string){return this.request({method:"signMessage",params:{message,address}})}sendKaspa(params:unknown){return this.request({method:"sendKaspa",params})}sendKRC20(params:unknown){return this.request({method:"sendKRC20",params})}sendKCC20(params:unknown){return this.request({method:"sendKCC20",params})}signPskt(params:unknown){return this.request({method:"signPskt",params})}transferKRC721(params:unknown){return this.request({method:"transferKRC721",params})}transferKNS(params:unknown){return this.request({method:"transferKNS",params})}}
interface KaspireProvider{connect():Promise<string[]>;pushTx(transaction:string):Promise<unknown>;signPolicyTransaction(params:unknown):Promise<unknown>}
KaspireProvider.prototype.connect=function(){return this.requestAccounts()};
KaspireProvider.prototype.pushTx=function(transaction:string){return this.request({method:"pushTx",params:transaction})};
KaspireProvider.prototype.signPskt=function(first:unknown,options?:unknown){return this.request({method:"signPskt",params:typeof first==="string"?{txJsonString:first,options}:first})};
KaspireProvider.prototype.signPolicyTransaction=function(params:unknown){return this.request({method:"signPolicyTransaction",params})};
const provider=new KaspireProvider();Object.defineProperty(window,"kaspire",{value:provider,configurable:false,writable:false});dispatchEvent(new CustomEvent("kaspire#initialized"));declare global{interface Window{kaspire:KaspireProvider}}
