const root=document.querySelector<HTMLElement>("#app")!;
const id=new URL(location.href).searchParams.get("id")??"";
void load();
async function load(){try{const [response,statusResponse]=await Promise.all([chrome.runtime.sendMessage({kind:"approval",command:"get",id}),chrome.runtime.sendMessage({channel:"wallet",command:"status"})]);if(response?.error)throw new Error(response.error.message);if(statusResponse?.error)throw new Error(statusResponse.error.message);const item=response.result;if(statusResponse.result?.locked){renderUnlock(item);return}renderApproval(item)}catch(error){renderError(error)}}
function renderUnlock(item:any){root.innerHTML=`<main><p class="eyebrow">DAPP CONNECTION</p><h1>Unlock Kaspire</h1><section><h2>${esc(item.origin)}</h2><p>This site is waiting to connect. Unlock your wallet before reviewing the request.</p><label>Vault password<input id="password" type="password" autocomplete="current-password" autofocus></label><p id="unlock-error" class="error"></p></section><div class="actions"><button id="cancel" class="ghost">CANCEL</button><button id="unlock">UNLOCK</button></div><p class="note">Unlocking does not connect the site. You will review and approve the connection next.</p></main>`;const password=document.querySelector<HTMLInputElement>("#password")!,button=document.querySelector<HTMLButtonElement>("#unlock")!,error=document.querySelector<HTMLElement>("#unlock-error")!;const unlock=async()=>{button.disabled=true;error.textContent="";try{const response=await chrome.runtime.sendMessage({channel:"wallet",command:"unlock",password:password.value});if(response?.error)throw new Error(response.error.message);renderApproval(item)}catch(caught){error.textContent=(caught as Error).message;password.select();button.disabled=false}};document.querySelector<HTMLButtonElement>("#cancel")!.onclick=()=>resolve(false);button.onclick=unlock;password.onkeydown=(event)=>{if(event.key==="Enter")void unlock()};password.focus()}
function renderApproval(item:any){root.innerHTML=`<main><p class="eyebrow">SECURE APPROVAL</p><h1>${esc(item.title)}</h1><section><h2>${esc(item.origin)}</h2><p>${esc(item.description)}</p>${item.details.map((detail:string)=>`<p>${esc(detail)}</p>`).join("")}${item.rawJson!=null?`<details class="raw-json"><summary>Raw JSON output</summary><pre>${esc(JSON.stringify(item.rawJson,(_key:string,value:unknown)=>typeof value==="bigint"?String(value):value,2))}</pre></details>`:""}</section><div class="actions"><button id="reject" class="ghost">REJECT</button><button id="approve">APPROVE</button></div><p class="note">Verify the site and every detail. Kaspire never signs silently.</p></main>`;document.querySelector<HTMLButtonElement>("#reject")!.onclick=()=>resolve(false);document.querySelector<HTMLButtonElement>("#approve")!.onclick=()=>resolve(true)}
function renderError(error:unknown){root.innerHTML=`<main><h1>Request unavailable</h1><p class="error">${esc((error as Error).message)}</p></main>`}
async function resolve(approved:boolean){await chrome.runtime.sendMessage({kind:"approval",command:"resolve",id,approved});close()}
function esc(value:string){const node=document.createElement("span");node.textContent=value;return node.innerHTML}
export{};
