import assert from "node:assert/strict";
import { spawn } from "node:child_process";
import { createServer } from "node:http";
import { mkdtemp, readFile, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join, resolve } from "node:path";

const debugPort=9331;const sitePort=8879;const profile=await mkdtemp(join(tmpdir(),"kaspire-browser-test-"));
const fixture=await readFile(new URL("./fixtures/dapp.html",import.meta.url));
const server=createServer((request,response)=>{if(request.url==="/dapp.html"){response.writeHead(200,{"content-type":"text/html"});response.end(fixture)}else{response.writeHead(404);response.end()}});
await new Promise(resolveReady=>server.listen(sitePort,"127.0.0.1",resolveReady));
const browser=spawn("chromium",["--headless=new","--no-sandbox","--disable-gpu",`--user-data-dir=${profile}`,`--disable-extensions-except=${resolve("dist")}`,`--load-extension=${resolve("dist")}`,`--remote-debugging-port=${debugPort}`,"about:blank"],{stdio:"ignore"});

async function targets(){for(let attempt=0;attempt<80;attempt++){try{return await(await fetch(`http://127.0.0.1:${debugPort}/json/list`)).json()}catch{await delay(100)}}throw new Error("Chromium debugging endpoint did not start.")}
async function open(url){return(await(await fetch(`http://127.0.0.1:${debugPort}/json/new?${encodeURIComponent(url)}`,{method:"PUT"})).json()).webSocketDebuggerUrl}
function evaluate(webSocketDebuggerUrl,expression){return new Promise((resolveValue,reject)=>{const socket=new WebSocket(webSocketDebuggerUrl);const timer=setTimeout(()=>{socket.close();reject(new Error("CDP evaluation timed out."))},50000);socket.onopen=()=>socket.send(JSON.stringify({id:1,method:"Runtime.evaluate",params:{expression,returnByValue:true,awaitPromise:true}}));socket.onerror=reject;socket.onmessage=event=>{const message=JSON.parse(event.data);if(message.id!==1)return;clearTimeout(timer);socket.close();if(message.result?.exceptionDetails)reject(new Error(message.result.exceptionDetails.exception?.description??message.result.exceptionDetails.text));else resolveValue(message.result?.result?.value)}})}
function command(webSocketDebuggerUrl,method,params={}){return new Promise((resolveValue,reject)=>{const socket=new WebSocket(webSocketDebuggerUrl);const timer=setTimeout(()=>{socket.close();reject(new Error("CDP command timed out."))},8000);socket.onopen=()=>socket.send(JSON.stringify({id:1,method,params}));socket.onerror=reject;socket.onmessage=event=>{const message=JSON.parse(event.data);if(message.id!==1)return;clearTimeout(timer);socket.close();message.error?reject(new Error(message.error.message)):resolveValue(message.result)}})}
async function observe(webSocketDebuggerUrl){const events=[];const socket=new WebSocket(webSocketDebuggerUrl);await new Promise((resolveReady,reject)=>{socket.onerror=reject;socket.onopen=()=>{socket.send(JSON.stringify({id:1,method:"Runtime.enable"}));socket.send(JSON.stringify({id:2,method:"Log.enable"}));resolveReady()}});socket.onmessage=event=>events.push(JSON.parse(event.data));return{events,close:()=>socket.close()}}
const delay=milliseconds=>new Promise(resolveDelay=>setTimeout(resolveDelay,milliseconds));
async function waitFor(page,expression){for(let attempt=0;attempt<60;attempt++){try{if(await evaluate(page,expression))return}catch{}await delay(100)}throw new Error(`Browser condition did not become true: ${expression}`)}

try{
  let worker;for(let attempt=0;attempt<80&&!worker;attempt++){worker=(await targets()).find(target=>target.type==="service_worker");if(!worker)await delay(100)}assert(worker,"Extension service worker did not load.");const extensionId=new URL(worker.url).host;const browserTarget=await(await fetch(`http://127.0.0.1:${debugPort}/json/version`)).json();
  const wallet=await open(`chrome-extension://${extensionId}/wallet.html`);await waitFor(wallet,'Boolean(document.querySelector("#first-create"))');assert.match(String(await evaluate(wallet,"document.body.innerText")),/Your Kaspa[.]?\s+Your Control/i);await evaluate(wallet,'document.querySelector("#first-create").click();true');await waitFor(wallet,'Boolean(document.querySelector("#password"))');
  await evaluate(wallet,'document.querySelector("#password").value="browser smoke test password 2026";document.querySelector("#password-confirm").value="browser smoke test password 2026";document.querySelector("#submit").click();true');await delay(3000);
  assert.match(String(await evaluate(wallet,"document.body.innerText")),/Recovery Phrase/i);const words=await evaluate(wallet,'JSON.stringify([...document.querySelectorAll("[data-word]")].map(input=>input.value))');const walletTarget=(await targets()).find(target=>target.url===`chrome-extension://${extensionId}/wallet.html`);assert(walletTarget,"Wallet target disappeared.");await command(browserTarget.webSocketDebuggerUrl,"Target.closeTarget",{targetId:walletTarget.id});const reopenedWallet=await open(`chrome-extension://${extensionId}/wallet.html`);await waitFor(reopenedWallet,'Boolean(document.querySelector("#verify"))');assert.match(String(await evaluate(reopenedWallet,"document.body.innerText")),/Recovery Phrase/i);await evaluate(reopenedWallet,'document.querySelector("#verify").click();true');await waitFor(reopenedWallet,'document.querySelectorAll("[data-check]").length===3');await evaluate(reopenedWallet,`(()=>{const words=${words};for(const input of document.querySelectorAll("[data-check]"))input.value=words[Number(input.dataset.check)];document.querySelector("#finish").click();return true})()`);await delay(1200);assert.match(String(await evaluate(reopenedWallet,"document.body.innerText")),/Assets & Names/i);
  const portableBackup=JSON.parse(String(await evaluate(reopenedWallet,'(async()=>{const response=await chrome.runtime.sendMessage({channel:"wallet",command:"exportBackup",password:"portable backup password 2026"});if(response.error)throw new Error(response.error.message);return response.result})()')));assert.equal(portableBackup.format,"kaspire-backup-v2");assert.equal(portableBackup.kdf,"argon2id-v19");assert.equal(portableBackup.memoryKiB,32768);assert.equal(portableBackup.iterations,3);assert.equal(portableBackup.parallelism,1);assert.equal(typeof portableBackup.ciphertext,"string");assert.equal("secret" in portableBackup,false);
  const restoreResult=await evaluate(reopenedWallet,`(async()=>{const response=await chrome.runtime.sendMessage({channel:"wallet",command:"importBackup",password:"portable backup password 2026",backup:${JSON.stringify(JSON.stringify(portableBackup))}});return response.error?"error:"+response.error.message:String(response.result)})()`);assert.equal(restoreResult,"true");
  await command(browserTarget.webSocketDebuggerUrl,"Target.closeTarget",{targetId:worker.id});await delay(300);
  const dapp=await open(`http://127.0.0.1:${sitePort}/dapp.html`);await waitFor(dapp,'document.querySelector("#result")?.textContent==="provider-ok"');assert.equal(await evaluate(dapp,'document.querySelector("#result").textContent'),"provider-ok");
  await evaluate(dapp,'window.connectResult="pending";window.kaspire.requestAccounts().then(value=>window.connectResult=JSON.stringify(value)).catch(error=>window.connectResult="error:"+error.message);true');await delay(500);
  let approval=(await targets()).find(target=>target.url.includes("approval.html"));assert(approval,"Connect approval did not open.");await waitFor(approval.webSocketDebuggerUrl,'Boolean(document.querySelector("#approve"))');assert.match(String(await evaluate(approval.webSocketDebuggerUrl,"document.body.innerText")),/Connect dApp/);await evaluate(approval.webSocketDebuggerUrl,'document.querySelector("#approve").click();true');await delay(500);assert.match(String(await evaluate(dapp,"window.connectResult")),/^\["kaspa:/);
  await evaluate(dapp,'window.signResult="pending";window.kaspire.signMessage("Kaspire browser smoke test").then(value=>window.signResult=JSON.stringify(value)).catch(error=>window.signResult="error:"+error.message);true');await delay(500);
  approval=(await targets()).find(target=>target.url.includes("approval.html"));assert(approval,"Signature approval did not open.");await waitFor(approval.webSocketDebuggerUrl,'Boolean(document.querySelector("#approve"))');assert.match(String(await evaluate(approval.webSocketDebuggerUrl,"document.body.innerText")),/Kaspire browser smoke test/);await evaluate(approval.webSocketDebuggerUrl,'document.querySelector("#approve").click();true');await delay(500);assert.match(String(await evaluate(dapp,"window.signResult")),/[0-9a-f]{128}/);
  const liveWorker=(await targets()).find(target=>target.type==="service_worker");assert(liveWorker,"Asset test service worker is unavailable.");const workerObserver=await observe(liveWorker.webSocketDebuggerUrl);const prepareResponse=JSON.parse(String(await evaluate(reopenedWallet,'(async()=>{const status=(await chrome.runtime.sendMessage({channel:"wallet",command:"status"})).result;const address=status.selectedAddress;await chrome.storage.session.set({assetReviewSnapshot:{address,network:"mainnet",loadedAt:Date.now(),assets:{tokens:[{symbol:"TEST",raw_balance:"100",decimals:0}],domains:[],krc721:[],kcc20:[],transactions:[]}}});return await new Promise(resolve=>{const stages=[];const port=chrome.runtime.connect({name:"wallet-operation"});const timeout=setTimeout(()=>{port.disconnect();resolve(JSON.stringify({timedOut:true,stages}))},40000);port.onMessage.addListener(value=>{if(value.progress){stages.push(value.progress);return}clearTimeout(timeout);port.disconnect();resolve(JSON.stringify({...value,stages}))});port.onDisconnect.addListener(()=>{clearTimeout(timeout);resolve(JSON.stringify({disconnected:true,error:chrome.runtime.lastError?.message,stages}))});port.postMessage({channel:"wallet",command:"prepareAsset",kind:"krc20",to:address,ticker:"TEST",amount:"1",displayAmount:"1"})})})()')));await delay(300);workerObserver.close();assert(prepareResponse?.result||prepareResponse?.error,`Asset prepare port returned no structured response: ${JSON.stringify(prepareResponse)} worker=${JSON.stringify(workerObserver.events)}`);
  await evaluate(dapp,'window.networkEvent="pending";window.kaspire.on("networkChanged",value=>window.networkEvent=value);window.kaspire.switchNetwork("testnet-10").then(value=>window.switchResult=value).catch(error=>window.switchResult="error:"+error.message);true');await delay(500);
  approval=(await targets()).find(target=>target.url.includes("approval.html"));assert(approval,"Network approval did not open.");await waitFor(approval.webSocketDebuggerUrl,'Boolean(document.querySelector("#approve"))');await evaluate(approval.webSocketDebuggerUrl,'document.querySelector("#approve").click();true');await delay(500);assert.equal(await evaluate(dapp,"window.switchResult"),"testnet-10");assert.equal(await evaluate(dapp,"window.networkEvent"),"testnet-10");
  console.log("Kaspire Chromium smoke test passed.");
}finally{browser.kill("SIGTERM");if(browser.exitCode===null)await new Promise(resolveExit=>{browser.once("exit",resolveExit);setTimeout(resolveExit,3000)});server.close();await rm(profile,{recursive:true,force:true,maxRetries:5,retryDelay:100})}
