import test from 'node:test';
import assert from 'node:assert/strict';
import {nftPublish,nftMyListings} from './generated/nftMarket.mjs';
const address='kaspa:seller-public-fixture',storageKey=`nftMarketRecoveryV1:${address}`;
function record(){return {seller:address,localId:'fixture-public-id',listingTransactionId:'a'.repeat(64),stage:'complete',status:'active',published:false,ticker:'TEST',tokenId:'1'};}
async function mocked(fetcher,run){const oldFetch=globalThis.fetch,oldChrome=globalThis.chrome,oldTimeout=globalThis.setTimeout;const store={[storageKey]:[record()]};globalThis.chrome={storage:{local:{get:async key=>({[key]:structuredClone(store[key])}),set:async value=>Object.assign(store,structuredClone(value))}}};globalThis.fetch=fetcher;globalThis.setTimeout=(callback,_ms,...args)=>oldTimeout(callback,0,...args);try{await run(store);}finally{globalThis.fetch=oldFetch;globalThis.chrome=oldChrome;globalThis.setTimeout=oldTimeout;}}
test('automatic NFT publication retries official indexer lag and marks Published without a manual button',async()=>{let calls=0;await mocked(async()=>++calls===1?new Response(JSON.stringify({error:'Indexer has not confirmed this NFT listing yet; retry Publish'}),{status:400}):new Response('{}',{status:201}),async store=>{await nftPublish(record());assert.equal(store[storageKey][0].published,true);assert.equal(calls,2);});});
test('concurrent publication requests coalesce and clean up without a promise cycle',async()=>{let calls=0;await mocked(async()=>{calls++;return new Response('{}',{status:201});},async()=>{await Promise.all([nftPublish(record()),nftPublish(record())]);assert.equal(calls,1);await nftPublish(record());assert.equal(calls,2);});});
test('publication rejection persists an actionable error instead of endless retries',async()=>{let calls=0;await mocked(async()=>{calls++;return new Response(JSON.stringify({error:'Invalid seller signature'}),{status:400});},async store=>{await assert.rejects(nftPublish(record()),/Invalid seller signature/);assert.equal(store[storageKey][0].publicationBlocked,true);assert.equal(store[storageKey][0].publicationError,'Invalid seller signature');assert.equal(calls,1);});});
test('late successful publication cannot resurrect a cancelled listing',()=>mocked(async()=>new Response('{}',{status:201}),async store=>{store[storageKey][0].status='cancelled';await nftPublish(record());assert.equal(store[storageKey][0].status,'cancelled');assert.equal(store[storageKey][0].published,false);}));
test('a stale active directory response cannot overwrite local cancellation or a known rarity rank',()=>mocked(async()=>new Response(JSON.stringify({offers:[{...record(),status:'active',rarityRank:null}],nextOffset:null})),async store=>{store[storageKey][0].status='cancelled';store[storageKey][0].rarityRank=114;const result=await nftMyListings(address);assert.equal(result.records[0].status,'cancelled');assert.equal(result.records[0].rarityRank,114);}));
