import test from "node:test";
import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import init,{addressWithPrefix,deriveBackupKey,deriveEvmAddress,exportEvmPrivateKey,generateWallet,generateWalletWithWordCount,importWallet,mnemonicWordStatus,prepareEvmTransaction,prepareInscription,preparePskt,publicKey,signEvmTransaction,signPersonalMessage,signPskt}from"./generated/wasm/kaspa_secure_core.mjs";

await init(await readFile(new URL("./generated/wasm/kaspa_secure_core_bg.wasm",import.meta.url)));

test("browser WASM creates and deterministically restores a wallet",()=>{const created=JSON.parse(generateWallet(""));assert.equal(created.mnemonic.split(" ").length,24);const restored=JSON.parse(importWallet(created.mnemonic,""));assert.equal(restored.address,created.address);assert.match(publicKey(`mnemonic:${created.mnemonic}`),/^[0-9a-f]{64}$/)});
test("browser WASM creates requested 12 and 24 word wallets",()=>{for(const count of[12,24]){const created=JSON.parse(generateWalletWithWordCount("optional passphrase",count));assert.equal(created.mnemonic.split(" ").length,count);assert.match(created.address,/^kaspa:/)}assert.throws(()=>generateWalletWithWordCount("",18))});
test("browser WASM preserves ownership across TN10 prefix conversion",()=>{const created=JSON.parse(generateWallet(""));assert.match(addressWithPrefix(created.address,true),/^kaspatest:/)});
test("browser WASM derives a 256-bit backup key",()=>assert.match(deriveBackupKey("correct horse battery staple","07".repeat(32)),/^[0-9a-f]{64}$/));
test("browser WASM uses the canonical BIP-39 list for feedback",()=>{const status=JSON.parse(mnemonicWordStatus("aboot aban"));assert.deepEqual(status.invalidWords,["aboot","aban"]);assert(status.suggestions.includes("abandon"))});
test("browser WASM builds reviewed canonical assets and KIP-5 signatures",()=>{const wallet=JSON.parse(generateWallet(""));const secret=`mnemonic:${wallet.mnemonic}`;const plan=JSON.parse(prepareInscription(JSON.stringify({kind:"krc20",sender:wallet.address,recipient:wallet.address,ticker:"TEST",amount:"1",tokenId:"",assetId:""})));assert.equal(plan.namespace,"kasplex");assert.match(signPersonalMessage(secret,wallet.address,"WASM integration test"),/^[0-9a-f]{128}$/)});
test("browser WASM derives, exports, reviews and signs Kasplex and Igra transactions",()=>{const wallet=JSON.parse(generateWallet("")),secret=`hd-path:m/44'/111111'/0'/0/0:mnemonic:${wallet.mnemonic}`,from=deriveEvmAddress(secret);assert.match(from,/^0x[0-9a-f]{40}$/);assert.match(exportEvmPrivateKey(secret),/^[0-9a-f]{64}$/);for(const chainId of[202555,38833]){const request={walletAddress:wallet.address,from,to:from,recipient:from,valueWei:"1",nonce:0,gasLimit:21000,gasPriceWei:"1000000000",chainId,data:"",tokenSymbol:chainId===202555?"KAS":"iKAS",displayAmount:"0.000000000000000001"},review=JSON.parse(prepareEvmTransaction(JSON.stringify(request))),signed=JSON.parse(signEvmTransaction(secret,JSON.stringify(request),review.reviewHash));assert.match(review.reviewHash,/^[0-9a-f]{64}$/);assert.match(signed.rawTransaction,/^0x[0-9a-f]+$/);assert.match(signed.transactionHash,/^0x[0-9a-f]{64}$/)}});
test("browser WASM preserves marketplace PSKT metadata and explicit sighash",()=>{const wallet=JSON.parse(generateWallet("")),secret=`mnemonic:${wallet.mnemonic}`,script=`000020${publicKey(secret)}ac`,transaction={version:0,inputs:[{transactionId:"44".repeat(32),index:0,sequence:"0",sigOpCount:1,signatureScript:"",marketplaceInput:{listing:"kept"},utxo:{amount:"200000000",scriptPublicKey:script,blockDaaScore:"100",isCoinbase:false}}],outputs:[{value:"199000000",scriptPublicKey:script,marketplaceOutput:{royalty:"kept"}}],subnetworkId:"0000000000000000000000000000000000000000",lockTime:"0",gas:"0",storageMass:"0",payload:"",marketplaceMetadata:{standard:"kaspacom"}},request={sender:wallet.address,txJsonString:JSON.stringify(transaction),signInputs:[{index:0,sighashType:132}],scripts:[]},review=JSON.parse(preparePskt(JSON.stringify(request))),signed=JSON.parse(signPskt(secret,JSON.stringify(request),review.reviewHash)),result=JSON.parse(signed.signedTxJson);assert.equal(review.inputs[0].sighashType,132);assert.deepEqual(result.marketplaceMetadata,transaction.marketplaceMetadata);assert.deepEqual(result.inputs[0].marketplaceInput,transaction.inputs[0].marketplaceInput);assert.deepEqual(result.outputs[0].marketplaceOutput,transaction.outputs[0].marketplaceOutput);assert.match(result.inputs[0].signatureScript,/^[0-9a-f]+$/)});
test("browser WASM assembles an ordered KaspaCom script request",()=>{const wallet=JSON.parse(generateWallet("")),secret=`mnemonic:${wallet.mnemonic}`,transaction={version:0,inputs:[{transactionId:"55".repeat(32),index:0,sequence:"0",sigOpCount:1,signatureScript:"",marketplaceInput:{listing:"kept"},utxo:{amount:"200000000",scriptPublicKey:"0000aa2077bd0b38d98df2c68287223096c04d85670d0b32316848f749bfce8436f217a187",blockDaaScore:"100",isCoinbase:false}}],outputs:[{value:"199000000",scriptPublicKey:`000020${publicKey(secret)}ac`,marketplaceOutput:{royalty:"kept"}}],subnetworkId:"0000000000000000000000000000000000000000",lockTime:"0",gas:"0",storageMass:"0",payload:"",marketplaceMetadata:{standard:"kaspacom",preserve:true}},request={sender:wallet.address,txJsonString:JSON.stringify(transaction),signInputs:[{index:0,sighashType:132}],scripts:[{inputIndex:0,scriptHex:"2079be667ef9dcbbac55a06295ce870b07029bfcdb2dce28d959f2815b16f81798",signatureScript:{mode:"ordered-args",args:[{type:"data",hex:"cafe"},{type:"signature",prefixHex:"01"},{type:"i64",value:"9"},{type:"byte",value:255}]}}]},review=JSON.parse(preparePskt(JSON.stringify(request))),signed=JSON.parse(signPskt(secret,JSON.stringify(request),review.reviewHash)),result=JSON.parse(signed.signedTxJson);assert.equal(review.inputs[0].signatureScriptMode,"ordered-args");assert.equal(review.inputs[0].sighashType,132);assert(result.inputs[0].signatureScript.endsWith(request.scripts[0].scriptHex));assert.deepEqual(result.marketplaceMetadata,transaction.marketplaceMetadata)});
